### PR TITLE
Run without issues on redhat systems and update drawio. 

### PR DESCRIPTION
**Pull request by Mosibi**

### CODE REVIEW

**Review by CoMPaTech — APPROVED** [review]
Looking good, I'll write up some flows as well to quickly test functionality

**Comment by CoMPaTech** [comment]
@Mosibi Actions will bork if we merge I presume (because the action still runs the old shell-script and requirements moved on) - we can just merge (as apparently you can't rerun newer actions on existing PRs) and fix with another PR or fix it in the PR. Both are fine with me :)

**Comment by Mosibi** [comment]
> @Mosibi Actions will bork if we merge I presume (because the action still runs the old shell-script and requirements moved on) - we can just merge (as apparently you can't rerun newer actions on existing PRs) and fix with another PR or fix it in the PR. Both are fine with me :)

Let’s just merge it and fix any issues later, if they occur

**Comment by CoMPaTech** [comment]
👍

**Pull request merged**
